# flake8: noqa

import os

FLASK_HOST = os.getenv("FLASK_HOST", "0.0.0.0")
FLASK_PORT = os.getenv("FLASK_PORT", "8000")
DEBUG = os.getenv("DEBUG", True)

VECTOR_SEARCH_SERVICE_TYPE = os.getenv("VECTOR_SEARCH_SERVICE_TYPE", None)

SEARCH_SERVICE_NAME = os.getenv("SEARCH_SERVICE_NAME", None)
SEARCH_SERVICE_INDEX_NAME = os.getenv("SEARCH_SERVICE_INDEX_NAME", None)
SEARCH_SERVICE_API_KEY = os.getenv("SEARCH_SERVICE_API_KEY", None)
SEARCH_SERVICE_API_VERSION = os.getenv("SEARCH_SERVICE_API_VERSION", None)

EMBEDDING_MODEL_ENDPOINT = os.getenv("EMBEDDING_MODEL_ENDPOINT", None)
EMBEDDING_MODEL_API_KEY = os.getenv("EMBEDDING_MODEL_API_KEY", None)


AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY", None)
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", None)
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", None)
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", None)

SERP_API_KEY = os.getenv("SERP_API_KEY", None)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", None)
OPENAI_API_ENDPOINT_CHAT_COMPLEATIONS = os.getenv("OPENAI_API_ENDPOINT_CHAT_COMPLEATIONS", None)
OPENAI_API_ENDPOINT_EMBEDDINGS = os.getenv("OPENAI_API_ENDPOINT_EMBEDDINGS", None)
